"""create_keywords_table

Revision ID: 41cc5b0b7475
Revises: 6dd7e98301ba
Create Date: 2024-03-21 12:33:03.005059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41cc5b0b7475'
down_revision: Union[str, None] = '6dd7e98301ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keywords',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('receive_text', sa.Text(), nullable=False),
    sa.Column('reply_text', sa.Text(), nullable=False),
    sa.Column('reply_voice_path', sa.Text(), nullable=True),
    sa.Column('reply_image_path', sa.Text(), nullable=True),
    sa.Column('registrant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['registrant_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('keywords')
    # ### end Alembic commands ###
