"""create_user_table

Revision ID: 6dd7e98301ba
Revises: 8f85466d5c50
Create Date: 2024-03-17 11:10:55.471852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dd7e98301ba'
down_revision: Union[str, None] = '8f85466d5c50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('mid', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=20), server_default='noname', nullable=False),
    sa.Column('picture_status', sa.Text(), nullable=True),
    sa.Column('level', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('exp', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('authority', sa.Enum('NORMAL', 'ADMIN', name='authority'), server_default='NORMAL', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
